# サーバーのIPアドレス
SERVER_IP = 172.20.1.219

## 無線通信デバイスとの通信関連 ##
# サーバーの画像をアップロードする
upload-image:
	curl --fail -X POST -F "file=@$(FILE_PATH)" http://$(SERVER_IP):8000/images

# ミニフィグの正面らしさ比較用画像をサーバーにアップロードする
upload-minifig-image:
	curl --fail -X POST -F "file=@$(FILE_PATH)" http://$(SERVER_IP):8000/minifig/detect
