name: Format Check

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          find ./ ./tests ./modules ./yolo_detection_system/modules -type f \( -name "*.cpp" -o -name "*.h" \) \
          | xargs clang-format --dry-run --Werror
