name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev
          sudo apt-get install -y nlohmann-json3-dev

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build Docker image
      #   run: docker buildx build --platform linux/arm64 --load -t myimage:arm64 .

      # - name: Run tests in container
      #   run: |
      #     docker run --rm -v $(pwd):/RasPike-ART/sdk/workspace/etrobocon2025 myimage:arm64 \
      #     bash -c "cd /RasPike-ART/sdk/workspace/etrobocon2025 && make test"

      # 今のところはコンテナを使わずに直接実行する．
      # もしコンテナによるテスト実施が可能であれば，
      # これをコメントアウトして，以上を有効化する．
      - name: Run tests
        run: |
          make test   